site_name: DVIA Docs
plugins:
  - with-pdf:
      cover_subtitle: DVIA内部文档
      cover: true
      cover_logo: logo/LOGO.png
      output_path: pdf/full.pdf
  - git-revision-date
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - extra
  - tables
  - smarty
  - toc:
      permalink: true
theme:
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - primary: deep orange
    - accent: yellow
  name: material
  logo: logo/LOGO.png
  favicon: logo/LOGO.png
  font: false
  locale: zh_CN
  language: zh
nav:
  - "欢迎": index.md
  - "概况":
      - "社团历史": "info/history.md"
      - "社团工作": "info/work.md"
  - "管理":
      - "组织架构": "man/org.md"
      - "加入社团": "man/join.md"
  - "技术":
      - "tech/entry.md"
      - "入门":
          - "拍摄": "tech/basic/rec.md"
          - "剪辑": "tech/basic/cut.md"
          - "直播": "tech/basic/stream.md"
      - "进阶":
          - "拍摄": "tech/adv/rec.md"
          - "剪辑": "tech/adv/cut.md"
          - "直播": "tech/adv/stream.md"
      - "精通":
          - "拍摄": "tech/pro/rec.md"
          - "剪辑": "tech/pro/cut.md"
          - "直播": "tech/pro/stream.md"
  - "标签": tags.md
  - "贡献": thanks.md
repo_url: https://github.com/Github-DVIA/DVIA
repo_name: Github-DVIA/DVIA
site_author: DVIA
copyright: Copyright &copy; 2008 - Now DVIA
edit_uri: ""
