site_name: DVIA Docs
plugins:
  - git-revision-date
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - extra
  - tables
  - smarty
  - toc:
      permalink: true
theme:
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.sections
    # toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  name: material
  logo: logo/LOGO.png
  favicon: logo/LOGO.png
  font: false
  locale: zh_CN
  language: zh
nav:
  - "欢迎": index.md
  - "社团概况":
      - "社团历史": "info/history.md"
      - "社团工作": "info/work.md"
  - "社团管理":
      - "组织架构": "org.md"
      - "加入社团": "join.md"
  - "技术参考":
      - "技术入门": "basic/entry.md"
      - "拍摄入门": "basic/rec.md"
      - "剪辑入门": "basic/cut.md"
      - "直播入门": "basic/stream.md"
  - "标签": tags.md
  - "项目贡献": thanks.md
